### ISSUE TITLE
Cannot add Locations of differing worlds

### ISSUE THREAD

**Issue by stitchinger** [hmzel/ParticleSFX#5]
Trying to get the spiral working with this code: 
```
            hm.zelha.particlesfx.particles.parents.Particle cherry = new ParticleCherryLeaves(0, 0, 0, 2);
            World world = player.getWorld();
            Location loc = player.getLocation();
            LocationSafe locationSafe = new LocationSafe(world, loc.getX(), loc.getY(),loc.getZ());
            CircleInfo circle1 = new CircleInfo(locationSafe,1);
            LocationSafe locationSafe2 = new LocationSafe(world, loc.getX(), loc.getY() + 2,loc.getZ());
            CircleInfo circle2 = new CircleInfo(locationSafe2,2);


            ParticleSpiral spiral = new ParticleSpiral(cherry, 2, 10, circle1, circle2);
            spiral.display();
```

and getting this error. Do I use it wrong?

```
Caused by: java.lang.IllegalArgumentException: Cannot add Locations of differing worlds
	at org.bukkit.Location.add(Location.java:360) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at Particle-API_1.21.jar/hm.zelha.particlesfx.shapers.parents.RotationHandler.calculateCentroid(RotationHandler.java:192) ~[Particle-API_1.21.jar:?]
	at Particle-API_1.21.jar/hm.zelha.particlesfx.shapers.parents.RotationHandler.recalculateIfNeeded(RotationHandler.java:143) ~[Particle-API_1.21.jar:?]
	at Particle-API_1.21.jar/hm.zelha.particlesfx.shapers.ParticleSpiral.recalculateIfNeeded(ParticleSpiral.java:194) ~[Particle-API_1.21.jar:?]
	at Particle-API_1.21.jar/hm.zelha.particlesfx.shapers.ParticleSpiral.setWorld(ParticleSpiral.java:227) ~[Particle-API_1.21.jar:?]
	at Particle-API_1.21.jar/hm.zelha.particlesfx.shapers.ParticleSpiral.<init>(ParticleSpiral.java:37) ~[Particle-API_1.21.jar:?]
	at Particle-API_1.21.jar/hm.zelha.particlesfx.shapers.ParticleSpiral.<init>(ParticleSpiral.java:42) ~[Particle-API_1.21.jar:?]
	at Particle-API_1.21.jar/io.georgeous.particle_api.PapiCommand.onCommand(PapiCommand.java:106) ~[Particle-API_1.21.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	... 26 more
```

**Comment by KazakEz** [comment]
Same exception.
Solution in https://github.com/hmzel/ParticleSFX/blob/master/src/main/java/hm/zelha/particlesfx/shapers/parents/RotationHandler.java#L192 replace to `centroid.add(locations.get(i).toVector());`, because this method have checks if world not "world"
![img](https://github.com/user-attachments/assets/89493108-3cbc-4aee-9d71-837a5a8ad1fa)

**Comment by stitchinger** [comment]
> Same exception. Solution: Replace https://github.com/hmzel/ParticleSFX/blob/master/src/main/java/hm/zelha/particlesfx/shapers/parents/RotationHandler.java#L192 to `centroid.add(locations.get(i).toVector());` Explanation: this method have checks if world is not similar and all these fields can use only in default world "world" ![img](https://private-user-images.githubusercontent.com/70358000/360603149-91f523f9-0d05-425a-9fa1-08cd998f0d8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjY2MzksIm5iZiI6MTcyNDY2NjMzOSwicGF0aCI6Ii83MDM1ODAwMC8zNjA2MDMxNDktOTFmNTIzZjktMGQwNS00MjVhLTlmYTEtMDhjZDk5OGYwZDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA5NTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyODg0YzNlNDM1ZmViMTA3YjhiYzdiZjA5NmQ2NThiYmIxNThmMjZmMjFkZDM5ZjM4YzcxZmNjYzkzOWRlNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ETkNmnKxA7BYLN4ZNqWyT2MwaqfwBj0L_N6VMWg4Pos) ![img](https://private-user-images.githubusercontent.com/70358000/360602674-89493108-3cbc-4aee-9d71-837a5a8ad1fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjY2MzksIm5iZiI6MTcyNDY2NjMzOSwicGF0aCI6Ii83MDM1ODAwMC8zNjA2MDI2NzQtODk0OTMxMDgtM2NiYy00YWVlLTlkNzEtODM3YTVhOGFkMWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA5NTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYTJkZWVmZDVjOTQyMjIzZjEwYzFmNjdlMjczOWNlNDEwZTUxZjZiMmU1ZTU2ODBkY2ZlOTk4Mzg3OTFlM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pPtPNFdTJ_au-sFeL624NIIX7yFu9RsjST8hEH9qTss)

Thank you very much. 
I cloned the repo locally, made the chage you suggested and built the jar.
But how do I use it? The minecraft server says it is missing the plugin.yml

**Comment by hmzel** [comment]
Damn, i tested every shape in another dimension, how did this sneak through ???
I'll re-release the packages with this and a few other things fixed in the next few days.
